In [1]:
import transformers
import shap
import numpy
import matplotlib.pylab as plt
import pandas as pd
import numpy as np
import scipy
from transformers import pipeline
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [2]:
import torch

In [54]:
tokenizer = AutoTokenizer.from_pretrained("unitary/toxic-bert")

model = AutoModelForSequenceClassification.from_pretrained("unitary/toxic-bert")

pred = transformers.pipeline("text-classification", model=model, tokenizer=tokenizer, return_all_scores=True)

In [105]:
text = "ill kill you"
X = tokenizer(text, return_tensors='pt')
y = model(**X)

In [106]:
scores = scipy.special.expit(y.logits.detach().numpy())[0]

In [107]:
labels = ["toxic","severe_toxic","obscene","threat","insult","identity_hate"]

In [108]:
for i in range(len(scores)):
    print(labels[i], ": ", np.round(scores[i], 2))

toxic :  0.93
severe_toxic :  0.15
obscene :  0.11
threat :  0.89
insult :  0.19
identity_hate :  0.06


[[{'label': 'toxic', 'score': 0.8704692125320435},
  {'label': 'severe_toxic', 'score': 0.00865361001342535},
  {'label': 'obscene', 'score': 0.061189282685518265},
  {'label': 'threat', 'score': 0.01115700788795948},
  {'label': 'insult', 'score': 0.03484519198536873},
  {'label': 'identity_hate', 'score': 0.013685752637684345}]]

In [109]:
explainer = shap.Explainer(pred)

In [117]:
shapley_values = explainer(np.array([text]))

In [118]:
shap.plots.text(shapley_values

In [112]:
shapley_values

.values =
array([[[-2.40098924e-07, -1.05155903e-07,  3.75390520e-07,
          1.84047587e-07, -1.37568531e-07,  5.08966968e-07],
        [ 6.29956226e-01, -1.20046559e+00, -1.16598193e+00,
         -7.71311976e-01, -1.36735638e-01, -9.58040337e-01],
        [-1.73975169e+00,  9.74946677e-01, -7.66823324e-01,
          4.11299545e+00, -1.55047658e+00, -9.78854259e-01],
        [ 1.27355249e+00, -1.86193595e+00, -1.12142307e+00,
         -1.17859245e+00, -7.01668376e-01, -1.49074790e+00],
        [-4.80197848e-07, -2.10311805e-07,  7.50781040e-07,
          3.68095174e-07, -2.75137062e-07,  1.01793394e-06]]])

.base_values =
array([[ 0.30378321, -2.71189163, -2.06961581, -2.74985795, -2.13207448,
        -2.38712821]])

.data =
array([['', 'ill ', 'kill ', 'you', '']], dtype='<U5')

In [114]:
shapley_values.values[0,:, 3]

array([ 1.84047587e-07, -7.71311976e-01,  4.11299545e+00, -1.17859245e+00,
        3.68095174e-07])